import type { Comment, Product, DashboardOverview, Recommendation } from "./types"

export const mockComments: Comment[] = [
  {
    id: "c1",
    text: "ស្អាតណាស់ ខ្ញុំចូលចិត្ត 😍",
    productMentioned: "Summer Dress",
    sentiment: "positive",
    sentimentScore: 0.92,
    date: "2026-02-25",
    author: "Sokha M.",
    likes: 14,
  },
  {
    id: "c2",
    text: "ថ្លៃពេក មិនសមនឹងតម្លៃ",
    productMentioned: "Laptop Bag",
    sentiment: "negative",
    sentimentScore: 0.25,
    date: "2026-02-24",
    author: "Dara K.",
    likes: 3,
  },
  {
    id: "c3",
    text: "ដឹកយូរពេកហើយ មិនទាន់មកដល់",
    productMentioned: "Samsung S23",
    sentiment: "negative",
    sentimentScore: 0.18,
    date: "2026-02-23",
    author: "Vanny C.",
    likes: 7,
  },
  {
    id: "c4",
    text: "quality laor nas នឹងទិញទៀត",
    productMentioned: "Wireless Earphones",
    sentiment: "positive",
    sentimentScore: 0.88,
    date: "2026-02-22",
    author: "Pheaktra S.",
    likes: 21,
  },
  {
    id: "c5",
    text: "battery ot sok bonthe",
    productMentioned: "iPhone 15",
    sentiment: "negative",
    sentimentScore: 0.2,
    date: "2026-02-21",
    author: "Rith N.",
    likes: 5,
  },
  {
    id: "c6",
    text: "shipping លឿនណាស់ អរគុណ",
    productMentioned: "Running Shoes",
    sentiment: "positive",
    sentimentScore: 0.85,
    date: "2026-02-20",
    author: "Chenda L.",
    likes: 18,
  },
  {
    id: "c7",
    text: "Cabin មានអារម្មណ៍ទំនើប និងផាសុខភាព",
    productMentioned: "Electric Vehicle",
    sentiment: "positive",
    sentimentScore: 0.9,
    date: "2026-02-19",
    author: "Bopha T.",
    likes: 25,
  },
  {
    id: "c8",
    text: "Maintenance EV នៅតំបន់ខ្លះអាចពិបាក",
    productMentioned: "Electric Vehicle",
    sentiment: "negative",
    sentimentScore: 0.3,
    date: "2026-02-18",
    author: "Kosal V.",
    likes: 9,
  },
  {
    id: "c9",
    text: "Range ឆ្ងាយ អាចធ្វើដំណើរឆ្ងាយដោយមិនបារម្ភ",
    productMentioned: "Electric Vehicle",
    sentiment: "positive",
    sentimentScore: 0.87,
    date: "2026-02-17",
    author: "Maly P.",
    likes: 16,
  },
  {
    id: "c10",
    text: "Design ស្អាត but screen ងាយនឹងឆ្កូត",
    productMentioned: "Samsung S23",
    sentiment: "neutral",
    sentimentScore: 0.5,
    date: "2026-02-16",
    author: "Visal K.",
    likes: 11,
  },
  {
    id: "c11",
    text: "ពណ៌ស្អាតខ្លាំង ចូលចិត្តម៉ូដែលនេះ",
    productMentioned: "Summer Dress",
    sentiment: "positive",
    sentimentScore: 0.91,
    date: "2026-02-15",
    author: "Sreymom H.",
    likes: 22,
  },
  {
    id: "c12",
    text: "Sound quality ល្អណាស់ សម្រាប់តម្លៃនេះ",
    productMentioned: "Wireless Earphones",
    sentiment: "positive",
    sentimentScore: 0.86,
    date: "2026-02-15",
    author: "Chanthy R.",
    likes: 15,
  },
  {
    id: "c13",
    text: "មិនទាន់បានទទួល 3 សប្តាហ៍ហើយ",
    productMentioned: "Watch",
    sentiment: "negative",
    sentimentScore: 0.15,
    date: "2026-02-14",
    author: "Narith B.",
    likes: 4,
  },
  {
    id: "c14",
    text: "Coffee maker ល្អ ធ្វើកាហ្វេឆ្ងាញ់",
    productMentioned: "Coffee Maker",
    sentiment: "positive",
    sentimentScore: 0.89,
    date: "2026-02-13",
    author: "Kunthea S.",
    likes: 19,
  },
  {
    id: "c15",
    text: "Backpack ធន់ used every day no problem",
    productMentioned: "Backpack",
    sentiment: "positive",
    sentimentScore: 0.83,
    date: "2026-02-12",
    author: "Piseth L.",
    likes: 12,
  },
  {
    id: "c16",
    text: "Sunglasses ទម្រង់ស្អាត but lens ងាយខូច",
    productMentioned: "Sunglasses",
    sentiment: "neutral",
    sentimentScore: 0.48,
    date: "2026-02-11",
    author: "Sokunthea M.",
    likes: 6,
  },
  {
    id: "c17",
    text: "iPhone camera ល្អឥតខ្ចោះ love it",
    productMentioned: "iPhone 15",
    sentiment: "positive",
    sentimentScore: 0.94,
    date: "2026-02-10",
    author: "Raksmey T.",
    likes: 28,
  },
  {
    id: "c18",
    text: "Shoes size មិនត្រូវ ប្តូរពិបាក",
    productMentioned: "Running Shoes",
    sentiment: "negative",
    sentimentScore: 0.22,
    date: "2026-02-09",
    author: "Sopheak N.",
    likes: 8,
  },
  {
    id: "c19",
    text: "Laptop bag material ស្អាត professional look",
    productMentioned: "Laptop Bag",
    sentiment: "positive",
    sentimentScore: 0.8,
    date: "2026-02-08",
    author: "Thida K.",
    likes: 10,
  },
  {
    id: "c20",
    text: "Normal ធម្មតា មិនមានអ្វីពិសេស",
    productMentioned: "Backpack",
    sentiment: "neutral",
    sentimentScore: 0.52,
    date: "2026-02-07",
    author: "Channary V.",
    likes: 2,
  },
]

export const mockProducts: Product[] = [
  {
    id: "p1",
    name: "iPhone 15",
    category: "Electronics",
    mentionCount: 48,
    positivePercent: 72,
    negativePercent: 18,
    neutralPercent: 10,
    avgSentimentScore: 0.74,
    comments: mockComments.filter((c) => c.productMentioned === "iPhone 15"),
    keywords: [
      { word: "camera", sentiment: "positive", count: 24 },
      { word: "battery", sentiment: "negative", count: 12 },
      { word: "design", sentiment: "positive", count: 18 },
      { word: "price", sentiment: "negative", count: 8 },
    ],
    trendData: [
      { date: "Feb 1", positive: 8, negative: 3, neutral: 1 },
      { date: "Feb 8", positive: 10, negative: 2, neutral: 2 },
      { date: "Feb 15", positive: 12, negative: 4, neutral: 1 },
      { date: "Feb 22", positive: 9, negative: 3, neutral: 2 },
    ],
  },
  {
    id: "p2",
    name: "Samsung S23",
    category: "Electronics",
    mentionCount: 35,
    positivePercent: 60,
    negativePercent: 25,
    neutralPercent: 15,
    avgSentimentScore: 0.62,
    comments: mockComments.filter((c) => c.productMentioned === "Samsung S23"),
    keywords: [
      { word: "screen", sentiment: "positive", count: 15 },
      { word: "shipping", sentiment: "negative", count: 10 },
      { word: "design", sentiment: "positive", count: 12 },
      { word: "scratch", sentiment: "negative", count: 6 },
    ],
    trendData: [
      { date: "Feb 1", positive: 5, negative: 3, neutral: 2 },
      { date: "Feb 8", positive: 7, negative: 2, neutral: 1 },
      { date: "Feb 15", positive: 6, negative: 4, neutral: 3 },
      { date: "Feb 22", positive: 8, negative: 3, neutral: 2 },
    ],
  },
  {
    id: "p3",
    name: "Wireless Earphones",
    category: "Electronics",
    mentionCount: 42,
    positivePercent: 85,
    negativePercent: 8,
    neutralPercent: 7,
    avgSentimentScore: 0.87,
    comments: mockComments.filter((c) => c.productMentioned === "Wireless Earphones"),
    keywords: [
      { word: "quality", sentiment: "positive", count: 22 },
      { word: "sound", sentiment: "positive", count: 20 },
      { word: "comfort", sentiment: "positive", count: 14 },
      { word: "battery", sentiment: "neutral", count: 5 },
    ],
    trendData: [
      { date: "Feb 1", positive: 10, negative: 1, neutral: 1 },
      { date: "Feb 8", positive: 12, negative: 1, neutral: 1 },
      { date: "Feb 15", positive: 11, negative: 0, neutral: 2 },
      { date: "Feb 22", positive: 13, negative: 1, neutral: 0 },
    ],
  },
  {
    id: "p4",
    name: "Summer Dress",
    category: "Fashion",
    mentionCount: 56,
    positivePercent: 90,
    negativePercent: 3,
    neutralPercent: 7,
    avgSentimentScore: 0.92,
    comments: mockComments.filter((c) => c.productMentioned === "Summer Dress"),
    keywords: [
      { word: "beautiful", sentiment: "positive", count: 30 },
      { word: "color", sentiment: "positive", count: 25 },
      { word: "style", sentiment: "positive", count: 20 },
      { word: "size", sentiment: "neutral", count: 8 },
    ],
    trendData: [
      { date: "Feb 1", positive: 14, negative: 1, neutral: 1 },
      { date: "Feb 8", positive: 16, negative: 0, neutral: 2 },
      { date: "Feb 15", positive: 15, negative: 1, neutral: 1 },
      { date: "Feb 22", positive: 18, negative: 0, neutral: 2 },
    ],
  },
  {
    id: "p5",
    name: "Running Shoes",
    category: "Fashion",
    mentionCount: 38,
    positivePercent: 68,
    negativePercent: 22,
    neutralPercent: 10,
    avgSentimentScore: 0.68,
    comments: mockComments.filter((c) => c.productMentioned === "Running Shoes"),
    keywords: [
      { word: "shipping", sentiment: "positive", count: 18 },
      { word: "size", sentiment: "negative", count: 12 },
      { word: "comfortable", sentiment: "positive", count: 15 },
      { word: "quality", sentiment: "positive", count: 10 },
    ],
    trendData: [
      { date: "Feb 1", positive: 7, negative: 3, neutral: 1 },
      { date: "Feb 8", positive: 8, negative: 2, neutral: 2 },
      { date: "Feb 15", positive: 9, negative: 4, neutral: 1 },
      { date: "Feb 22", positive: 7, negative: 3, neutral: 1 },
    ],
  },
  {
    id: "p6",
    name: "Electric Vehicle",
    category: "Automotive",
    mentionCount: 31,
    positivePercent: 75,
    negativePercent: 20,
    neutralPercent: 5,
    avgSentimentScore: 0.76,
    comments: mockComments.filter((c) => c.productMentioned === "Electric Vehicle"),
    keywords: [
      { word: "cabin", sentiment: "positive", count: 14 },
      { word: "range", sentiment: "positive", count: 12 },
      { word: "maintenance", sentiment: "negative", count: 8 },
      { word: "modern", sentiment: "positive", count: 10 },
    ],
    trendData: [
      { date: "Feb 1", positive: 6, negative: 2, neutral: 0 },
      { date: "Feb 8", positive: 7, negative: 1, neutral: 1 },
      { date: "Feb 15", positive: 8, negative: 3, neutral: 0 },
      { date: "Feb 22", positive: 7, negative: 2, neutral: 1 },
    ],
  },
  {
    id: "p7",
    name: "Coffee Maker",
    category: "Home",
    mentionCount: 22,
    positivePercent: 82,
    negativePercent: 10,
    neutralPercent: 8,
    avgSentimentScore: 0.82,
    comments: mockComments.filter((c) => c.productMentioned === "Coffee Maker"),
    keywords: [
      { word: "taste", sentiment: "positive", count: 12 },
      { word: "easy", sentiment: "positive", count: 10 },
      { word: "quality", sentiment: "positive", count: 8 },
      { word: "price", sentiment: "neutral", count: 4 },
    ],
    trendData: [
      { date: "Feb 1", positive: 5, negative: 1, neutral: 1 },
      { date: "Feb 8", positive: 6, negative: 0, neutral: 1 },
      { date: "Feb 15", positive: 5, negative: 1, neutral: 0 },
      { date: "Feb 22", positive: 7, negative: 1, neutral: 1 },
    ],
  },
  {
    id: "p8",
    name: "Laptop Bag",
    category: "Accessories",
    mentionCount: 28,
    positivePercent: 55,
    negativePercent: 30,
    neutralPercent: 15,
    avgSentimentScore: 0.56,
    comments: mockComments.filter((c) => c.productMentioned === "Laptop Bag"),
    keywords: [
      { word: "material", sentiment: "positive", count: 10 },
      { word: "price", sentiment: "negative", count: 14 },
      { word: "professional", sentiment: "positive", count: 8 },
      { word: "value", sentiment: "negative", count: 6 },
    ],
    trendData: [
      { date: "Feb 1", positive: 4, negative: 3, neutral: 1 },
      { date: "Feb 8", positive: 5, negative: 2, neutral: 2 },
      { date: "Feb 15", positive: 3, negative: 4, neutral: 1 },
      { date: "Feb 22", positive: 4, negative: 3, neutral: 2 },
    ],
  },
]

export const mockDashboardOverview: DashboardOverview = {
  totalComments: 1234,
  avgSentimentScore: 72,
  engagedProducts: 12,
  recommendationCount: 8,
  sentimentOverTime: [
    { date: "Feb 1", positive: 45, negative: 12, neutral: 8 },
    { date: "Feb 4", positive: 52, negative: 15, neutral: 10 },
    { date: "Feb 7", positive: 48, negative: 18, neutral: 7 },
    { date: "Feb 10", positive: 61, negative: 10, neutral: 12 },
    { date: "Feb 13", positive: 55, negative: 14, neutral: 9 },
    { date: "Feb 16", positive: 67, negative: 8, neutral: 11 },
    { date: "Feb 19", positive: 72, negative: 13, neutral: 6 },
    { date: "Feb 22", positive: 58, negative: 11, neutral: 10 },
    { date: "Feb 25", positive: 65, negative: 9, neutral: 8 },
    { date: "Feb 28", positive: 70, negative: 7, neutral: 12 },
  ],
  sentimentDistribution: [
    { name: "Positive", value: 68, fill: "oklch(0.65 0.2 155)" },
    { name: "Neutral", value: 18, fill: "oklch(0.65 0.01 250)" },
    { name: "Negative", value: 14, fill: "oklch(0.6 0.2 30)" },
  ],
  engagementVsSentiment: [
    { post: "Post 1", likes: 120, sentimentScore: 85 },
    { post: "Post 2", likes: 89, sentimentScore: 72 },
    { post: "Post 3", likes: 156, sentimentScore: 91 },
    { post: "Post 4", likes: 45, sentimentScore: 35 },
    { post: "Post 5", likes: 210, sentimentScore: 88 },
    { post: "Post 6", likes: 67, sentimentScore: 45 },
    { post: "Post 7", likes: 134, sentimentScore: 78 },
    { post: "Post 8", likes: 98, sentimentScore: 62 },
  ],
}

export const mockRecommendations: Recommendation = {
  topProducts: [
    {
      name: "Summer Dress",
      positivePercent: 90,
      praisePoints: ["Beautiful design", "Excellent colors", "Great value for money"],
    },
    {
      name: "Wireless Earphones",
      positivePercent: 85,
      praisePoints: ["Outstanding sound quality", "Comfortable fit", "Long battery life"],
    },
    {
      name: "Coffee Maker",
      positivePercent: 82,
      praisePoints: ["Makes great coffee", "Easy to use", "Durable build"],
    },
  ],
  needsImprovement: [
    {
      name: "Laptop Bag",
      negativePercent: 30,
      complaints: ["Overpriced", "Not worth the value", "Stitching issues"],
    },
    {
      name: "Samsung S23",
      negativePercent: 25,
      complaints: ["Screen scratches easily", "Slow shipping", "Battery drains fast"],
    },
    {
      name: "Running Shoes",
      negativePercent: 22,
      complaints: ["Incorrect sizing", "Difficult returns", "Sole wears quickly"],
    },
  ],
  insights: [
    {
      id: "i1",
      icon: "package",
      title: "Shipping complaints increasing",
      description: "Consider faster courier options. 23% of negative comments mention shipping delays.",
      type: "warning",
    },
    {
      id: "i2",
      icon: "dollar-sign",
      title: "Price sensitivity in Electronics",
      description: "Customers in the Electronics category are 40% more likely to mention price concerns.",
      type: "danger",
    },
    {
      id: "i3",
      icon: "star",
      title: "Summer Dress has 90% satisfaction",
      description: "Feature this product prominently in your next campaign for maximum engagement.",
      type: "success",
    },
    {
      id: "i4",
      icon: "refresh-cw",
      title: "Color variety requested",
      description: "Customers are asking for more color options in the Fashion category. Consider expanding the range.",
      type: "info",
    },
  ],
  trendingTopics: [
    { word: "quality", count: 45, sentiment: "positive" },
    { word: "shipping", count: 38, sentiment: "negative" },
    { word: "battery", count: 32, sentiment: "negative" },
    { word: "design", count: 30, sentiment: "positive" },
    { word: "price", count: 28, sentiment: "negative" },
    { word: "camera", count: 24, sentiment: "positive" },
    { word: "color", count: 22, sentiment: "positive" },
    { word: "comfortable", count: 20, sentiment: "positive" },
    { word: "sound", count: 18, sentiment: "positive" },
    { word: "material", count: 16, sentiment: "positive" },
    { word: "fast", count: 15, sentiment: "positive" },
    { word: "size", count: 14, sentiment: "negative" },
    { word: "scratch", count: 10, sentiment: "negative" },
    { word: "value", count: 12, sentiment: "neutral" },
    { word: "style", count: 11, sentiment: "positive" },
    { word: "modern", count: 9, sentiment: "positive" },
    { word: "maintenance", count: 8, sentiment: "negative" },
    { word: "range", count: 7, sentiment: "positive" },
    { word: "durable", count: 6, sentiment: "positive" },
    { word: "easy", count: 10, sentiment: "positive" },
  ],
}
